
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import * 
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("700x400")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 400,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    700.0,
    90.0,
    fill="#E0E9FF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    185.0,
    245.0,
    image=image_image_1
)

canvas.create_text(
    26.0,
    12.0,
    anchor="nw",
    text="Welcome to",
    fill="#000000",
    font=("Montserrat Medium", 15 * -1)
)

canvas.create_text(
    26.0,
    37.0,
    anchor="nw",
    text="Simple Torrent-like Application (STA)",
    fill="#0A27CF",
    font=("Montserrat ExtraBold", 24 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=377.0,
    y=189.0,
    width=300.0,
    height=40.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=377.0,
    y=258.0,
    width=300.0,
    height=40.0
)

canvas.create_text(
    26.0,
    127.0,
    anchor="nw",
    text="Email",
    fill="#000000",
    font=("Nunito Light", 10 * -1)
)

canvas.create_text(
    33.0,
    189.0,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("Nunito Light", 10 * -1)
)

canvas.create_text(
    26.0,
    251.0,
    anchor="nw",
    text="Re-password",
    fill="#000000",
    font=("Nunito Light", 10 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=36.0,
    y=326.0,
    width=300.0,
    height=35.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    185.5,
    287.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=36.0,
    y=270.0,
    width=299.0,
    height=32.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    185.5,
    225.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=36.0,
    y=208.0,
    width=299.0,
    height=32.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    185.5,
    163.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=36.0,
    y=146.0,
    width=299.0,
    height=32.0
)

canvas.create_rectangle(
    376.0,
    124.0,
    497.0,
    125.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    556.0,
    124.0,
    677.0,
    125.0,
    fill="#000000",
    outline="")

canvas.create_text(
    517.0,
    115.0,
    anchor="nw",
    text="OR",
    fill="#000000",
    font=("Montserrat Medium", 15 * -1)
)

canvas.create_text(
    446.0,
    326.0,
    anchor="nw",
    text="You have account?",
    fill="#000000",
    font=("Montserrat Regular", 10 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=546.0,
    y=326.0,
    width=40.0,
    height=10.0
)
window.resizable(False, False)
window.mainloop()
