
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("700x400")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 400,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    502.0,
    200.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    160.0,
    199.0,
    image=image_image_2
)

canvas.create_text(
    340.0,
    24.0,
    anchor="nw",
    text="Welcome to",
    fill="#0E0E0F",
    font=("Montserrat Bold", 12 * -1)
)

canvas.create_text(
    343.0,
    44.0,
    anchor="nw",
    text="Simple Torrent-like Application (STA)",
    fill="#0A27CF",
    font=("Montserrat ExtraBold", 16 * -1)
)

canvas.create_rectangle(
    344.0,
    195.0,
    465.0,
    196.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    524.0,
    195.0,
    645.0,
    196.0,
    fill="#000000",
    outline="")

canvas.create_text(
    487.0,
    186.0,
    anchor="nw",
    text="OR",
    fill="#000000",
    font=("Montserrat Medium", 15 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    495.0,
    224.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    495.0,
    270.0,
    image=image_image_4
)

canvas.create_text(
    375.0,
    206.0,
    anchor="nw",
    text="Email",
    fill="#000000",
    font=("Montserrat Light", 10 * -1)
)

canvas.create_text(
    372.0,
    250.0,
    anchor="nw",
    text="Passwork",
    fill="#000000",
    font=("Montserrat Light", 10 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    510.0,
    233.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=380.0,
    y=223.0,
    width=260.0,
    height=18.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=345.0,
    y=315.0,
    width=300.0,
    height=35.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    505.0,
    278.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=375.0,
    y=268.0,
    width=260.0,
    height=18.0
)

canvas.create_text(
    397.0,
    362.0,
    anchor="nw",
    text="Don’t have an account?",
    fill="#000000",
    font=("Montserrat Regular", 10 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=517.0,
    y=362.0,
    width=50.0,
    height=10.0
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    360.0,
    223.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    360.0,
    268.0,
    image=image_image_6
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=345.0,
    y=98.0,
    width=300.0,
    height=35.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=345.0,
    y=144.0,
    width=300.0,
    height=35.0
)
window.resizable(False, False)
window.mainloop()
