
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("700x400")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 400,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    350.0,
    15.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    350.0,
    45.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    350.0,
    75.0,
    image=image_image_3
)

canvas.create_text(
    42.0,
    6.0,
    anchor="nw",
    text="Simple Torrent-like Application (STA)",
    fill="#000000",
    font=("Montserrat Regular", 14 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=17.0,
    y=34.0,
    width=80.0,
    height=20.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=124.0,
    y=34.0,
    width=60.0,
    height=20.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=211.0,
    y=35.0,
    width=100.0,
    height=20.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=338.0,
    y=35.0,
    width=70.0,
    height=20.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    350.0,
    100.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    350.0,
    247.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    350.0,
    392.0,
    image=image_image_6
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=73.0,
    y=60.0,
    width=30.0,
    height=30.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=175.0,
    y=60.0,
    width=30.0,
    height=30.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=124.0,
    y=59.0,
    width=30.0,
    height=30.0
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    16.0,
    15.0,
    image=image_image_7
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=22.0,
    y=60.0,
    width=30.0,
    height=30.0
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    350.0,
    365.0,
    image=image_image_8
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=53.0,
    y=350.0,
    width=100.0,
    height=30.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=548.0,
    y=350.0,
    width=100.0,
    height=30.0
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    125.0,
    141.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    125.0,
    171.0,
    image=image_image_10
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    275.0,
    141.0,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    275.0,
    171.0,
    image=image_image_12
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    425.0,
    141.0,
    image=image_image_13
)

image_image_14 = PhotoImage(
    file=relative_to_assets("image_14.png"))
image_14 = canvas.create_image(
    425.0,
    171.0,
    image=image_image_14
)

image_image_15 = PhotoImage(
    file=relative_to_assets("image_15.png"))
image_15 = canvas.create_image(
    575.0,
    141.0,
    image=image_image_15
)

image_image_16 = PhotoImage(
    file=relative_to_assets("image_16.png"))
image_16 = canvas.create_image(
    575.0,
    171.0,
    image=image_image_16
)

canvas.create_text(
    95.0,
    131.0,
    anchor="nw",
    text="Name",
    fill="#000000",
    font=("Montserrat Bold", 14 * -1)
)

canvas.create_text(
    75.0,
    161.0,
    anchor="nw",
    text="abc.torrent",
    fill="#000000",
    font=("Montserrat Bold", 14 * -1)
)

canvas.create_text(
    251.0,
    131.0,
    anchor="nw",
    text="Size",
    fill="#000000",
    font=("Montserrat Bold", 14 * -1)
)

canvas.create_text(
    251.0,
    161.0,
    anchor="nw",
    text="700 MB",
    fill="#000000",
    font=("Montserrat Bold", 14 * -1)
)

canvas.create_text(
    393.0,
    131.0,
    anchor="nw",
    text="Seeders",
    fill="#000000",
    font=("Montserrat Bold", 14 * -1)
)

canvas.create_text(
    394.0,
    161.0,
    anchor="nw",
    text="10",
    fill="#000000",
    font=("Montserrat Bold", 14 * -1)
)

canvas.create_text(
    543.0,
    131.0,
    anchor="nw",
    text="Leechers",
    fill="#000000",
    font=("Montserrat Bold", 14 * -1)
)

canvas.create_text(
    548.0,
    161.0,
    anchor="nw",
    text="5",
    fill="#000000",
    font=("Montserrat Bold", 14 * -1)
)

image_image_17 = PhotoImage(
    file=relative_to_assets("image_17.png"))
image_17 = canvas.create_image(
    350.0,
    210.0,
    image=image_image_17
)

image_image_18 = PhotoImage(
    file=relative_to_assets("image_18.png"))
image_18 = canvas.create_image(
    352.0,
    237.0,
    image=image_image_18
)

image_image_19 = PhotoImage(
    file=relative_to_assets("image_19.png"))
image_19 = canvas.create_image(
    352.0,
    264.0,
    image=image_image_19
)

image_image_20 = PhotoImage(
    file=relative_to_assets("image_20.png"))
image_20 = canvas.create_image(
    352.0,
    291.0,
    image=image_image_20
)

image_image_21 = PhotoImage(
    file=relative_to_assets("image_21.png"))
image_21 = canvas.create_image(
    352.0,
    318.0,
    image=image_image_21
)

canvas.create_text(
    268.0,
    204.0,
    anchor="nw",
    text="Người upload: User123",
    fill="#000000",
    font=("Montserrat Light", 11 * -1)
)

canvas.create_text(
    268.0,
    230.0,
    anchor="nw",
    text="Ngày tạo: 01/01/2024",
    fill="#000000",
    font=("Montserrat Light", 11 * -1)
)

canvas.create_text(
    268.0,
    257.0,
    anchor="nw",
    text="Đã tải xong: 50 lần",
    fill="#000000",
    font=("Montserrat Light", 11 * -1)
)

canvas.create_text(
    268.0,
    284.0,
    anchor="nw",
    text="Đang tải: 5 người",
    fill="#000000",
    font=("Montserrat Light", 11 * -1)
)

canvas.create_text(
    268.0,
    311.0,
    anchor="nw",
    text="Đang chia sẻ: 10 người",
    fill="#000000",
    font=("Montserrat Light", 11 * -1)
)
window.resizable(False, False)
window.mainloop()
